- name: updates locale of machines
  hosts: "*"
  become: true
  tasks:
    - name: enable locales
      shell: >
        sed -i 's/^\# en_US.UTF-8 UTF-8$/en_US.UTF-8 UTF-8/g' /etc/locale.gen &&
        sed -i 's/^\# sv_SE.UTF-8 UTF-8$/sv_SE.UTF-8 UTF-8/g' /etc/locale.gen &&
        sed -i 's/^\# en_GB.UTF-8 UTF-8$/en_GB.UTF-8 UTF-8/g' /etc/locale.gen
    - name: generate locales
      shell: >
        locale-gen
    - name: update locales
      shell: >
        update-locale --reset LANG="en_US.UTF-8" LC_COLLATE="en_US.UTF-8" LC_CTYPE="sv_SE.UTF-8" LC_MESSAGES="en_GB.UTF-8" LC_MONETARY="en_US.UTF-8" LC_NUMERIC="en_US.UTF-8" LC_TIME="en_US.UTF-8"
