- name: installation and setup of Open SSH
  hosts: "*"
  become: true
  tasks:
    - name: install openssh-server
      apt:
        name: openssh-server
        state: present
        update_cache: true
    - name: remove old sshd_config
      shell: >
        rm /etc/ssh/sshd_config
    - name: add settings to new sshd_config
      shell: >
        echo "Include /etc/ssh/sshd_config.d/*.conf" > /etc/ssh/sshd_config &&
        echo "PasswordAuthentication no" >> /etc/ssh/sshd_config &&
        echo "PermitEmptyPasswords no" >> /etc/ssh/sshd_config &&
        echo "PermitRootLogin no" >> /etc/ssh/sshd_config &&
        echo "X11Forwarding no" >> /etc/ssh/sshd_config &&
        echo "HostKey /etc/ssh/ssh_host_rsa_key" >> /etc/ssh/sshd_config &&
        echo "HostKey /etc/ssh/ssh_host_ed25519_key" >> /etc/ssh/sshd_config
    - name: Re-generate RSA- and ED25519-keys
      shell: >
        rm /etc/ssh/ssh_host_* &&
        ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" &&
        ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""
    - name: Remove small Diffie-Hellman moduli
      shell: >
        awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe &&
        mv /etc/ssh/moduli.safe /etc/ssh/moduli
    - name: Enable RSA- and ED25519-keys
      shell: >
        sed -i 's/^\#HostKey \/etc\/ssh\/ssh_host_\(rsa\|ed25519\)_key$/HostKey \/etc\/ssh\/ssh_host_\1_key/g' /etc/ssh/sshd_config
    - name: Restrict supported key exchange, cipher, and MAC algorithms
      shell: >
        echo "\n# Restrict key exchange, cipher, and MAC algorithms, as per sshaudit.com\n# hardening guide.\nKexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256\nCiphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr\nMACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com\nHostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com" > /etc/ssh/sshd_config.d/ssh-audit_hardening.conf
    - name: Restart Open SSH
      shell: >
        systemctl restart ssh.service

